package com.schoolerp.enums;

public enum ClassStandard {
    NURSERY,FIRST,SECOND,THIRD,FOURTH,FIFTH,SIXTH,SEVENTH,EIGHTH,NINTH,TENTH,ELEVENTH,TWELFTH,UKG,LKG,PLAYGROUP,PRE_NURSERY,PRE_PRIMARY,PRIMARY
}
